In [1]:
from MomentumPyClient import Momentum
import pandas as pd
import time

m = Momentum()
m.get_status()

{'State': 'Offline', 'Attended': True, 'Simulated': True}

In [2]:
m.get_version()

{'Version': '7.3.0'}

In [3]:
m.stop()
m.get_status()

{'State': 'Offline', 'Attended': True, 'Simulated': True}

In [5]:
m.simulate()
time.sleep(4)
m.get_status()

{'State': 'Online', 'Attended': True, 'Simulated': True}

In [6]:
m.get_instrument_names()

['a4S',
 'Bioshake_1',
 'Bioshake_2',
 'Carousel',
 'DynaPro',
 'Echo',
 'Hotel',
 'Liconic_1',
 'Liconic_2',
 'Liconic_3',
 'Lidpark',
 'Mantis',
 'MicroSpin',
 'PassiveNest_1',
 'PassiveNest_2',
 'RotationStation',
 'SpinnakerBT_1',
 'SpinnakerBT_2',
 'Stunner',
 'SwapStation',
 'Tecan_Fluent',
 'Tecan_Spark',
 'Waste',
 'XPeel']

In [ ]:
m.get_process_names()

In [7]:
m.run_process("Process1")

{'WorkUnitsSubmitted': [{'Id': '6fef8bab-1c94-45ea-bad9-372a28052836',
   'Name': 'Work Unit 1960'}]}

In [8]:
pd.DataFrame(m.get_devices())

,Id,Name,Mode,State,OnlineState,Active,Available,DockState,Present,IsSimulated,IsInstrument,Priority,FirmwareVersion,SoftwareVersion,ModelDescription,SerialNumber,ConnectionMode,Type,IsWasteInstrument
0,4f51db55-ca7c-4727-81c1-f6f802364f7c,a4S,Normal,Online,Idle,False,True,Docked,True,True,True,2,515A,Communication Protocol 1.7,Not available.,Not available.,Unknown,4titude Automatic Roll Heat Sealer a4S,False
1,214e834c-f610-40cc-80ce-eb7942cddf06,ApplicationLauncher,Normal,Online,Idle,False,True,Docked,True,True,False,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Application Launcher,False
2,6043bfa4-3328-4cbc-a600-05afc956b7cc,Beacon,Normal,Online,Idle,False,True,Docked,True,True,False,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Beacon,False
3,3a7fddd5-cdc7-4978-a6d4-03e9819a565e,Bioshake_1,Normal,Online,Idle,False,True,Docked,True,True,True,2,1.8.00,Not available.,Q.MTP-BIOSHAKE 5000 elm,Not available.,Unknown,QInstruments BioShake 5000 Series - Single,False
4,51806669-d2ac-410a-8cae-f55dec5e03b1,Bioshake_2,Normal,Online,Idle,False,True,Docked,True,True,True,2,1.8.00,Not available.,Q.MTP-BIOSHAKE 5000 elm,Not available.,Unknown,QInstruments BioShake 5000 Series - Single,False
5,1335f9d0-6337-42fc-bc3a-d45ad209c15c,Carousel,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Thermotor Carousel - 8 Columns,False
6,d6659913-6630-4f50-8b9d-815da7740772,ContainerScanner,Normal,Online,Idle,False,True,Docked,True,True,False,2,N/A,3.0.0.0,Thermo.Momentum.ContainerScanner,N/A,Unknown,Thermo Scientific Container Scanner,False
7,eeba0e63-1fa1-4b4c-9db1-f22020d468a9,Docking,Normal,Online,Idle,False,True,Docked,True,True,False,0,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Docking Inputs Monitor,False
8,5dd5ab0d-1990-4061-9e20-2eaef1805c39,DynaPro,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Wyatt DynaPro,False
9,4037e7bd-b249-425a-92ce-ae24dfa14109,Echo,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,3.2.2,Echo 650,E6XX-22158,Unknown,Labcyte Echo6XX Acoustic Dispenser,False
10,afb5b5c3-c91e-49e3-8430-1de6f824e0f6,FileManager,Normal,Online,Idle,False,True,Docked,True,True,False,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific File Manager,False
11,a0387028-39c6-49f8-9f94-9e359b7aa6de,Hotel,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific General Incubator,False
12,593a806e-38bf-4c37-9830-b8e5cd5f0e52,Liconic_1,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,N/A,STX110,Not available.,Unknown,Liconic StoreX STX Series Incubator,False
13,b0a8db49-ee8c-4383-a878-cdcc5df4e8cb,Liconic_2,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,N/A,STX110,Not available.,Unknown,Liconic StoreX STX Series Incubator,False
14,9110a8a1-6564-447c-b639-07da8cabefbb,Liconic_3,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,N/A,STX110,Not available.,Unknown,Liconic StoreX STX Series Incubator,False
15,b1e7f0fd-0cdb-4f83-af68-0b1730f95c05,Lidpark,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Lid Park Station Delidder,False
16,778eed5c-429f-40ac-9f5f-2d478dbb27c0,Mantis,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Formulatrix Mantis,False
17,084a8047-733e-44bd-a110-ca04bfd6d77a,MicroSpin,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,HighRes MicroSpin Centrifuge,False
18,9c67eb09-1be9-4534-91b8-e83f57237e2e,MomentumOperator,Normal,Online,Idle,False,True,Docked,True,True,False,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Momentum Operator 4,False
19,ed1d474e-245c-46a7-8054-ab48a6b9379c,PassiveNest_1,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific General Incubator,False
20,1910398c-f5f7-4a4b-aa5e-2a8dcde99c79,PassiveNest_2,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific General Incubator,False
21,5969fdbb-72d4-41de-a7ea-ab8a036be7d3,RotationStation,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Rotation Station,False
22,2dc029f7-4437-40e6-8e82-8536ef567a54,SpinnakerBT_1,Normal,Online,Idle,False,True,Docked,True,True,True,1,Not available.,Thermo Scientific Mover Framework 2.4.30,Thermo Scientific Spinnaker with BenchTrak,Not available.,Unknown,Thermo Scientific Mover,False
23,dd83075e-9cb5-4347-8308-43b79ba1cacc,SpinnakerBT_2,Normal,Online,Idle,False,True,Docked,True,True,True,1,Not available.,Thermo Scientific Mover Framework 2.4.30,Thermo Scientific Spinnaker with BenchTrak,Not available.,Unknown,Thermo Scientific Mover,False
24,489733e8-11d1-4b91-b731-cfa5a4e45947,SwapStation,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific Swap Station,False
25,f47443eb-024d-477b-8cd4-708c8b02c957,Tecan_Fluent,Simulation,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Tecan Fluent,False
26,579119fc-de14-4743-b968-01abc7d1634c,Tecan_Spark,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Tecan Spark(Magellan),False
27,c5a69267-4d61-41c1-a357-0f954f2d5605,Waste,Normal,Online,Idle,False,True,Docked,True,True,True,2,Not available.,Not available.,Not available.,Not available.,Unknown,Thermo Scientific General Waste,True
28,5e30c241-4c66-41b0-9c5e-4722b015fa37,Wtio_Beacon,Normal,Online,Idle,False,True,Docked,True,True,False,0,Not available.,Not available.,Not available.,Not available.,Unknown,White Tree Technology WTIO-1 Input/Ouput,False
29,938c77b6-f4a5-4313-a5bf-4a9c76863963,Wtio_Lidpark,Normal,Online,Idle,False,True,Docked,True,True,False,0,Not available.,Not available.,Not available.,Not available.,Unknown,White Tree Technology WTIO-1 Input/Ouput,False
30,3701c66e-dfe3-49a0-a977-1bd3de521907,Wtio_Regrip,Normal,Online,Idle,False,True,Docked,True,True,False,0,Not available.,Not available.,Not available.,Not available.,Unknown,White Tree Technology WTIO-1 Input/Ouput,False
31,815d9399-7927-4c54-9fdb-fb811fe32c8b,XPeel,Normal,Online,Idle,False,True,Docked,True,True,True,2,2.11,N/A,Nexus Biosystems XPeel,,Unknown,Nexus Biosystems XPeel,False

In [ ]:
pd.DataFrame(m.get_containers())

In [ ]:
pd.DataFrame(m.get_barcodes("T_Plate1"))

In [ ]:
pd.DataFrame(m.get_barcodes("T_Plate1","Carousel"))

In [9]:
m.get_instrument_nests("Carousel")

{'Column1_Hotel': ['Nest 1',
  'Nest 2',
  'Nest 3',
  'Nest 4',
  'Nest 5',
  'Nest 6',
  'Nest 7',
  'Nest 8',
  'Nest 9',
  'Nest 10',
  'Nest 11',
  'Nest 12',
  'Nest 13',
  'Nest 14',
  'Nest 15'],
 'Column2_Hotel': ['Nest 1',
  'Nest 2',
  'Nest 3',
  'Nest 4',
  'Nest 5',
  'Nest 6',
  'Nest 7',
  'Nest 8',
  'Nest 9',
  'Nest 10',
  'Nest 11',
  'Nest 12',
  'Nest 13',
  'Nest 14',
  'Nest 15'],
 'Column3_Hotel': ['Nest 1',
  'Nest 2',
  'Nest 3',
  'Nest 4',
  'Nest 5',
  'Nest 6',
  'Nest 7',
  'Nest 8',
  'Nest 9',
  'Nest 10',
  'Nest 11',
  'Nest 12',
  'Nest 13',
  'Nest 14',
  'Nest 15'],
 'Column4_Hotel': ['Nest 1',
  'Nest 2',
  'Nest 3',
  'Nest 4',
  'Nest 5',
  'Nest 6',
  'Nest 7',
  'Nest 8',
  'Nest 9',
  'Nest 10',
  'Nest 11',
  'Nest 12',
  'Nest 13',
  'Nest 14',
  'Nest 15']}

In [10]:
df = pd.DataFrame(m.get_nests())
df

,Name,IsAccessible,IsVirtual,IsSink,IsStack,DeviceId,DeviceName,Content,StackContents
0,a4S:Nest,True,False,False,False,4f51db55-ca7c-4727-81c1-f6f802364f7c,a4S,None,[]
1,Bioshake_1:Nest,True,False,False,False,3a7fddd5-cdc7-4978-a6d4-03e9819a565e,Bioshake_1,None,[]
2,Bioshake_2:Nest,True,False,False,False,51806669-d2ac-410a-8cae-f55dec5e03b1,Bioshake_2,None,[]
3,Carousel:Column5_Stack1,True,False,False,True,1335f9d0-6337-42fc-bc3a-d45ad209c15c,Carousel,None,[]
4,Carousel:Column1_Hotel:Nest 1,True,False,False,False,1335f9d0-6337-42fc-bc3a-d45ad209c15c,Carousel,"{'ContainerName': '*T_Destination (Id: 840, Ba...",[]
...,...,...,...,...,...,...,...,...,...
257,Tecan_Fluent:Nest 20,True,False,False,False,f47443eb-024d-477b-8cd4-708c8b02c957,Tecan_Fluent,None,[]
258,Tecan_Fluent:Waste,True,False,True,False,f47443eb-024d-477b-8cd4-708c8b02c957,Tecan_Fluent,None,[]
259,Tecan_Spark:Nest 1,True,False,False,False,579119fc-de14-4743-b968-01abc7d1634c,Tecan_Spark,None,[]
260,Waste:Nest,True,False,True,False,c5a69267-4d61-41c1-a357-0f954f2d5605,Waste,None,[]
261,XPeel:Nest,True,False,False,False,815d9399-7927-4c54-9fdb-fb811fe32c8b,XPeel,None,[]

In [ ]:
df[df['DeviceName']=="MicroSpin"]

In [ ]:
containers = m.get_containers()
containers[0]

In [ ]:
ItemId = containers[0]["Inventory"]['ItemId']
ItemId

In [ ]:
attributes = m.get_item_attribute(ItemId)
attributes

In [ ]:
attributes

In [ ]:
items = [
                {
                    "Template": "T_Destination",
                    "Nest": "Carousel:Column2_Hotel:Nest 1",
                    "HasLid": False,
                    "Barcode" : "ABC123"
                }
           ]

m.add_inventyory_items(items)